//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ShareP", ConfigurationName="IShareP")]
public interface IShareP
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ShareP/IShareP/RequestServerInfo", ReplyAction="http://ShareP/IShareP/RequestServerInfoResponse")]
    System.Collections.Generic.Dictionary<string, string> RequestServerInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ShareP/IShareP/RequestServerInfo", ReplyAction="http://ShareP/IShareP/RequestServerInfoResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> RequestServerInfoAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ShareP/IShareP/ClientConnect", ReplyAction="http://ShareP/IShareP/ClientConnectResponse")]
    bool ClientConnect(System.Collections.Generic.Dictionary<string, string> clientInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ShareP/IShareP/ClientConnect", ReplyAction="http://ShareP/IShareP/ClientConnectResponse")]
    System.Threading.Tasks.Task<bool> ClientConnectAsync(System.Collections.Generic.Dictionary<string, string> clientInfo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISharePChannel : IShareP, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SharePClient : System.ServiceModel.ClientBase<IShareP>, IShareP
{
    
    public SharePClient()
    {
    }
    
    public SharePClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SharePClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SharePClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SharePClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Collections.Generic.Dictionary<string, string> RequestServerInfo()
    {
        return base.Channel.RequestServerInfo();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> RequestServerInfoAsync()
    {
        return base.Channel.RequestServerInfoAsync();
    }
    
    public bool ClientConnect(System.Collections.Generic.Dictionary<string, string> clientInfo)
    {
        return base.Channel.ClientConnect(clientInfo);
    }
    
    public System.Threading.Tasks.Task<bool> ClientConnectAsync(System.Collections.Generic.Dictionary<string, string> clientInfo)
    {
        return base.Channel.ClientConnectAsync(clientInfo);
    }
}
